version: "3.3"

services:
  backend:
    build: 
      context: ./springtest
      dockerfile: Dockerfile
    restart: unless-stopped
  frontend:
    build: 
      context: ./springbootreact
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./springbootreact/node_modules:/usr/app/node_modules
      - ./springbootreact:/usr/app
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
